### ISSUE TITLE
垂直和水平参考线问题

### ISSUE THREAD

**Issue by ggymm** [refline/refline.js#2]
在线示例：http://49.233.166.224/data-view-web/data-view-instance/create
代码：https://github.com/ggymm/data-view-web-preview

重现步骤：
1. 添加纵向参考线
2. 位移组件
点击图表组件进行位移操作会调用src/store/modules/data-view/refline.js中的setRefline方法，会获取所有横向和纵向的参考线，然后初始化refline
3. 移动时使用updater方法获取delta，但是没有触发吸附操作

我将吸附距离调大，并且添加横向参考线，出现了吸附现象（和吸附距离应该无关，只是调大会现象比较明显）。但是吸附位置不正确

麻烦帮忙看下是什么问题，多谢了

**Comment by bplok20010** [comment]
1. 吸附线参数你写反了 adsorbVLines 才是垂直吸附线
2. 参考线显示错乱是因为没正确处理缩放下的坐标， 缩放100%是正常的

**Comment by ggymm** [comment]
> 1. 吸附线参数你写反了 adsorbVLines 才是垂直吸附线
> 2. 参考线显示错乱是因为没正确处理缩放下的坐标， 缩放100%是正常的

感谢
横纵参考线的问题修复了: [commit](https://github.com/ggymm/data-view-web-preview/commit/cee77b258cad3c2682b22fc2dbf3c5f1166ce6fd)

但是缩放下的吸附还是有些问题
我设置给refline的值统一都为未缩放的值，包括元素的坐标和大小。所以这回我设置的默认横纵参考线也是取未缩放的值
但是吸附还是有些异常，而且多次测试发现每次触发吸附的位置并不一样

另外由于我设置的元素大小为实际值，导致取得元素中间位置不正确。
这个是否可以有个参数设置元素的真实大小。或者可以有个参数指定缩放比率

**Comment by bplok20010** [comment]
可，在adsorbCreator新增相应的缩放比率

**Comment by bplok20010** [comment]
@ggymm v0.8.0已经添加了，在你的示例代码中测试正常，如下：
```
updater = this.refline.adsorbCreator({
...,
scale
})

  const { delta } = updater({
     pageX: e.clientX,
     pageY: e.clientY
  })
  this.item.x += delta.left 
  this.item.y += delta.top 
```

**Comment by ggymm** [comment]
@bplok20010 感谢，测试正确。非常好用
